### ISSUE TITLE
Improve Azure Pipelines when pushing Artifacts

### ISSUE THREAD

**Issue by daviddesmet** [daviddesmet/NaCl.Core#64]
Skip duplicates when pushing a NuGet package to Azure Artifacts by passing `true` to `allowPackageConflicts`.

```yml
  - task: NuGetCommand@2
    displayName: 'Push NuGet'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'ffbd9fd0-ffca-4040-8576-0fa5065bd6d9/b465c74e-3671-458e-996f-8bbf45f957bc'
      allowPackageConflicts: true
```
